spring:
  application:
    name: velog

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liYzy1Y8H5Dguitt
            client-secret: 273a8a3c46a0bf99e56deef39ca57b024263d2b5
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/velog
    username: hwan
    password: hwan1487
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

server:
  port: 8080